### ISSUE TITLE
Problems detecting filesystem type

### ISSUE THREAD

**Issue by inof** [Emrion/uploaders#2]
First of all, thanks for this script! I think it can be very helpful in certain situations.

I tried to run the script on a machine of mine and got this output:

```
This utility helps to update the FreeBSD loaders.
show-me mode: it tells what it would do but changes nothing.

One or more efi partition(s) have been found.

mount -t msdosfs /dev/nda0p1 /mnt
[: : bad number
umount /mnt

One or more freebsd-boot partition(s) have been found.
The root file system is ufs.

Examining nda0...
[: : bad number
Would run: gpart bootcode -b /boot/pmbr -p /boot/gptboot -i 2 nda0

-------------------------------
Your current boot method is UEFI.
Boot device: nda0p1 File(\EFI\BOOT\BOOTX64.EFI)
Updatable BIOS loader: 1
-------------------------------
```

Note there are two error messages `[: : bad number`. This caused me to take a closer look at the script. The culprit are these grep commands in the script (lines 259 and 265):

```
                        r1="$(grep -c ZFS "$p")"
[...]
                        r2="$(grep -c zfs "$p")"
```

I have `GREP_OPTIONS=--binary-files=without-match` in my environment, so those grep commands produce no output and return with exit code 1 (because the raw partitions are binary). I suggest that the script performs `unset GREP_OPTIONS` at the beginning, so it works independently from individual user settings. Alternatively, pass the option `-U` to grep.

However, using grep like that is probably not a good idea anyway, because it reads the entire partition, including free blocks that might contain data of files that have been removed. Therefore the grep commands might cause false positives. It would be much better to mount the partition temporarily and look at the contents on filesystem-level.

**Comment by Emrion** [comment]
Thanks for showing me this issue. I can certainly add unset GREP_OPTIONS. But, it's impossible to mount a freebsd-boot partition as it is a raw type. No file system inside, so no mount.

Fix committed.

**Comment by inof** [comment]
Thanks!

Regarding the “freebsd-boot” partition, I was under the impression that it had to be a UFS file system …
```
inof@helium> gpart show nda0 | grep freebsd-boot
       82432         512     2  freebsd-boot  (256K)
inof@helium> fstyp /dev/nda0p2
ufs
```
But I haven’t booted that machine via legacy BIOS for many years (maybe never), so the freebsd-boot partition isn’t actually used. It’s ignored when booting via UEFI. I have to admit I have no idea why the freebsd-boot partition on the above box is UFS, and I have no idea if it actually worked (maybe not).

**Comment by Emrion** [comment]
Weird... You should avoid to boot in BIOS mode because:

```
% gpart show
=>       40  104857520  ada0  GPT  (50G)
         40     409600     1  efi  (200M)
     409640       1024     2  freebsd-boot  (512K)
     410664        984        - free -  (492K)
     411648    4194304     3  freebsd-swap  (2.0G)
    4605952  100249600     4  freebsd-zfs  (48G)
  104855552       2008        - free -  (1.0M)
```

```
% fstyp /dev/ada0p2
fstyp: /dev/ada0p2: filesystem not recognized
```
Or maybe, you should gpart bootcode -p the appropriate file between gptboot and gptzfsboot. For I wanted my script to verify the coherence with root file system, but it's also a limitation if something is wrong in this partition, as the code panics in some ways. :-)
